# Generated by Django 6.0.3 on 2026-04-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
